version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}-frontend:${IMAGE_TAG}
    ports:
      - "3000:80"   # Host 3000 → Container 80 (nginx serve karega build)
    environment:
      - VITE_BACKEND_URI=http://backend:3000   # container network ke liye backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}-backend:${IMAGE_TAG}
    ports:
      - "5000:3000"   # Host 5000 → Container 3000
    environment:
      - MONGODB_URI=mongodb+srv://DevSaini:dev1256@cluster0.pugztbw.mongodb.net/onsko
      - PORT=3000
      - JWT_SECRET=devsaini1256oiuoiuyfghvbnkloiuytfdghjkl
      - IMAGEKIT_PUBLIC_KEY=public_+kbNS5EXmIxczVGSE191mnneD+I=
      - IMAGEKIT_PRIVATE_KEY=private_9Vpa0x1TcIWbJGSg07LtXRdV2e4=
      - IMAGEKIT_ID=mkjyuczro
      - IMAGEKIT_URL=https://ik.imagekit.io/mkjyuczro
      - FRONTEND_URI=http://frontend:80   # container network ke liye frontend
